services:
  todo:
    build: /root/practice-host-todo-Dockerfile/micro-services/Todo/
    ports:
      - '80:80'
    container_name: todo_apache
    volumes:
      - v1:/var/www/html/
    network_mode: 
      bridge

  traffic:
    build: /root/practice-host-todo-Dockerfile/micro-services/Traffic/
    ports:
      - '81:80'
    container_name: traffic_apache
    volumes:
      - v2:/var/www/html/
    network_mode: 
      bridge

season:
    build: /root/practice-host-todo-Dockerfile/micro-services/Season/
    ports:
      - '82:80'
    container_name: season_apache
    volumes:
      - v3:/var/www/html/
    network_mode: 
      bridge
number:
    build: /root/practice-host-todo-Dockerfile/micro-services/Number/
    ports:
      - '82:80'
    container_name: number_apache
    volumes:
      - v4:/var/www/html/
    network_mode: 
      bridge

volumes:
    v1:
    v2:
    v3:
    v4: